# Generated by Django 2.1.2 on 2018-10-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('manager_name', models.CharField(max_length=255)),
                ('idea', models.CharField(max_length=255, null=True)),
                ('appliaction', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'admin'), (2, 'viewers'), (3, 'voters'), (4, 'player')], default='4', max_length=255),
        ),
        migrations.AddField(
            model_name='storeidea',
            name='store_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
