# Generated by Django 2.1.2 on 2018-10-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181024_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeidea',
            old_name='appliaction',
            new_name='application',
        ),
    ]
